server:
  http2:
    enabled: true
  port: 8443
  ssl:
    key-alias: localhost
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: password
spring:
  ai:
    ollama:
      chat:
        model: llama3.1
